ohap/ohap/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView #login
from django.urls import path
from info.views import info
from django.conf import settings
from django.conf.urls.static import static
from first.views import index,pub,create_comment,beer,delete_comment,create_recomment,delete_recomment,like
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index ,name='index'),
    path('pub/<int:mypub_id>', pub, name="pub"),
    path('create_comment/<int:mypub_id>',create_comment , name="create_comment"),
    path('delete_comment/<int:com_id>/<int:mypub_id>',delete_comment , name="delete_comment"),
    path('create_recomment/<int:mypub_id>',create_recomment , name="create_recomment"),
    path('delete_recomment/<int:recom_id>/<int:mypub_id>',delete_recomment, name="delete_recomment"),
    path('beer/<int:mymenu_id>',beer, name='beer'), 
    path('account/sign_up/',account_views.sign_up,name="sign_up"), #회원가입
    path('account/login/',LoginView.as_view(),name="login"), #로그인
    path('account/logout/',LogoutView.as_view(),name="logout"), #로그아웃
    path('like/<int:mylike_id>/<int:mymenu_id>/',like, name='like'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ohap/account/models.py
from django.db import models

# Create your models here.

ohap/first/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()
User.objects.all()
# Create your models here.
class Publist(models.Model):
    title = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.title

class Menulist(models.Model):
    Publist = models.ForeignKey(Publist, on_delete=models.CASCADE)
    body = models.CharField('메뉴',max_length=50)

    def __str__(self):
        return self.body

class Menudetail(models.Model):
    menulist = models.ForeignKey(Menulist, on_delete=models.CASCADE)
    pubname = models.CharField('펍이름',max_length=50)
    beername = models.CharField('맥주이름',max_length=50)
    beerimage = models.ImageField('이미지')
    likes = models.ManyToManyField(User, blank=True)
    taste = models.TextField('맛')
    information = models.TextField('정보')
    price =models.CharField('가격',max_length= 30)
    alcohol = models.CharField('알콜도수',max_length=30)
    
    def __str__(self):
        return self.beername

class Comment(models.Model):
    post = models.ForeignKey(Publist, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null = True, on_delete=models.CASCADE)
    body = models.CharField('댓글!',max_length=120)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null = True, on_delete=models.CASCADE)
    body = models.CharField('대댓글',max_length=150)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

ohap/info/models.py
from django.db import models
from django.conf import settings

class Beer(models.Model):
    pubname = models.TextField(null=True)
    beername = models.TextField(null=True)
    beerimage = models.ImageField(default = "null")
    # likes = models.ManyToManyField(user, blank=True)
    # 뒤에 settings~~는 user object뒤에 오는 값  settings.AUTH_USER_MODEL
    taste = models.TextField(null=True)
    information = models.TextField(null=True)
    price = models.TextField(null=True)
    alcohol = models.TextField(null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank = True)

    def __str__(self):
        return self.beername

 

# Create your models here.

ohap/account/forms.py
from django import forms
from .views import home, sign_up

ohap/first/forms.py
from django import forms
from .models import Comment,ReComment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body','post')


class ReCommentForm(forms.ModelForm):

    
    class Meta:
        model = ReComment
        fields = ('body','comment')

ohap/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm


def sign_up(request):
    if request.method == "POST":

        sign_up_form = UserCreationForm(request.POST)

        if sign_up_form.is_valid:
            sign_up_form.save()
            return redirect('index')

        else:
            return redirect('sign_up')

    sign_up_form = UserCreationForm()
    return render(request,'registration/sign_up.html',{'sign_up_form':sign_up_form})

# Create your views here.

ohap/first/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import CommentForm,ReCommentForm
from .models import Publist,Menulist,Menudetail,Comment,ReComment,User


# Create your views here.

def index(request):
    a = Publist.objects.all()
    return render(request,'index.html',{'a':a})

def pub(request, mypub_id):
    mypub = get_object_or_404(Publist,pk=mypub_id)
    menu = Menulist.objects.filter(Publist=mypub)
    
    
 
    #댓글
    mycom_form = CommentForm()
    myrecom_form = ReCommentForm()
    context = {'comment_form':mycom_form,'mypub':mypub,'menu':menu,'recomment_form':myrecom_form}
    return render(request, 'pub.html', context)

def beer(request, mymenu_id):
    mymenu = get_object_or_404(Menulist,pk=mymenu_id)
    mybeer = Menudetail.objects.filter(menulist=mymenu)
    
    # ilike = Menudetail.likes
    mymenu_id = mymenu_id
    context ={'mymenu':mymenu,'mybeer':mybeer,'mymenu_id':mymenu_id}
    return render(request, 'beer.html', context)


def create_comment(request, mypub_id):
    filled_form = CommentForm(request.POST)

    if filled_form.is_valid():
        a= filled_form.save(commit=False)
        a.author=request.user
        a.save()
    return redirect('pub', mypub_id)

def delete_comment(request, com_id,mypub_id):
    mycom = Comment.objects.get(id = com_id)
    mycom.delete()
    return redirect('pub', mypub_id)
    
def create_recomment(request, mypub_id):
    filled_form = ReCommentForm(request.POST) 

    if filled_form.is_valid():
        a= filled_form.save(commit=False)
        a.author=request.user
        a.save()
    return redirect('pub', mypub_id)

def delete_recomment(request, recom_id, mypub_id):
    myrecom = ReComment.objects.get(id = recom_id)
    myrecom.delete()
    return redirect('pub', mypub_id)

def like(request, mylike_id, mymenu_id):
    user = request.user
    print(mylike_id)
    if request.method == 'POST' and user.is_authenticated:
        # user = request.user
        # mylike = request.POST.get('pk', None)
        ilike = Menudetail.objects.get(pk = mylike_id)
        if ilike.likes.filter(id = user.id).exists():
            ilike.likes.remove(user)
        else:
            ilike.likes.add(user)
    else:
        return render(request,'index.html', {'login_flag' : True})
    context = {'likes_count' : ilike.likes}
    return redirect('beer', mymenu_id)

ohap/info/views.py
from django.shortcuts import render, get_object_or_404
from .models import Beer
from django.views.generic import RedirectView

def info(request):
    all_Beer = Beer.objects.all()
    context = {'take_all_Beer' : all_Beer}

    return render(request, 'info.html', context)

# class PostLikeRedirect(RedirectView):
#     def get_redirect_url(self, *args, **kwargs):
#         slug= self.kwargs.get("slug")
#         print(slug)
#         obj = get_object_or_404(Beer, slug=slug)
#         url_ = obj.get_absolute_url()
#         user = self.request.user
#         if user.is_authenticated():
#             if user in obj.likes.all()
#             obj.likes.add(user)
#         return url_ 

# def like(request, beer_id):
#     mylike = Beer.objects.get(pk=beer_id)
#     if Beer.like.filter(id=user.id).exists():
#         Beer.like.remove(user)
#     else:
#         Beer.like.add(user)
#     COUNTA(like)

#     context = {}
#     return render(request, 'info.html', context)

    
    




# Create your views here.

ohap/first/templates/beer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Beer</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/beer.css' %}">
    <style>
        img { display: block; margin: 0px auto; }
    </style>
</head>
<body>
    <div class="beer_info">
        <div class="login">
            {%if user.is_authenticated%}
                {{user.username}}님이 접속하셨습니다.
                <a href="{%url 'logout' %}">로그아웃</a>
            {%else%}
            <a href="{%url 'sign_up'%}">회원가입</a> 
            <a href="{%url 'login'%}">로그인</a>
            {%endif%}
            <a href=" {%url 'index'%}">
            </div>
            <header>
                <h3> PU </h3>
                <h3> NB </h3>
            </header>    
            </a>

        {% for i in mybeer %}
        <div class="beers">
            {{i.pubname}}<br>
        </div>
        <div class="beers">
            {{i.beername}}<br>
        </div>
        <img class="beerimg" src="{{i.beerimage.url}}">
        
        <form method="POST" action="{% url 'like' i.id mymenu_id %}">
            {% csrf_token %}
        <input type="submit" value="❤" class="likebutton"> 
            {{i.likes.count}}
        </form>
        
        <div class="beers">
            {{i.taste}}<br>
        </div>
        <div class="beers">
            {{i.price}}<br>
        </div>
        <div class="beers">
            {{i.alcohol}}<br>
        </div>
        <div class="beers">
            {{i.information}}<br>
        </div>
    </div>

    {% endfor %}
</body>
</html>

ohap/first/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width", initial-scale="1.0">
    <title> PNUB </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <script type="text/javascript">
        $(document).ready(function() {
            $(function() {
                $( "#some_flag" ).dialog({
                    modal: true,
                    closeOnEscape: false,
                    dialogClass: "no-close",
                    resizable: false,
                    draggable: false,
                    width: 600,
                    buttons: [
                        {
                            text: "OK",
                            click: function() {
                            $( this ).dialog( "close" );
                            }
                        }
                    ]
                });
            });
        });
    </script>
</head>
<body>
    <div class = "container">
        {% if login_flag %}
        <div id="login_flag" title="Login Flag">
            <p>로그인이 필요한 기능입니다</p>
         </div>
        {% endif %}
        <div class="top-page">
        <div class="login">
        {%if user.is_authenticated%}
            {{user.username}}님이 접속하셨습니다.
            <a href="{%url 'logout' %}"><button type="button" class="btn btn-light">로그아웃</button>
                </a>
        {%else%}
        <a href="{%url 'login'%}"><button type="button" class="btn btn-light">로그인</button>
        </a>
        <a href="{%url 'sign_up'%}"><button type="button" class="btn btn-light">회원가입</button>
        </a> 
        
        {%endif%}
        </div>
            <h3> PU <br> NB </h3>
            <h5 class='hello'>Welcome to our service</h5>
            <div class="service">
                we provide <div class="service-name">

                    <ul class="service-list">
                        <li>Pub list</li>
                        <li>Menu list</li>
                        <li>Menu detail</li>
                        <li>Pub list</li>
                    </ul>
                </div>
            </div>

    </div>


        <div class=pub_list>
        {% for mypub in a %}
        
        <a href="{% url 'pub' mypub.id %}">
            <div class="card" style="width: 18rem;">
                {% if mypub.image %}
                <img class="image" src="{{mypub.image.url}}" class="card-img-top"  alt="이미지">
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title">{{mypub.title}}</h5>
                  <p class="card-text">{{mypub.number}}</p>
                  <a href="{% url 'pub' mypub.id %}" class="btn btn-primary">Go Menulist</a>
                </div>
              </div>

            
        </a>
        {% endfor %}
        </div>
    
    </div>
    
</body>
</html>

ohap/first/templates/pub.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pub</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/pub.css' %}">
</head>
<body>
    <div class = "container">
        <div class="top">
        <div class="login">
            {%if user.is_authenticated%}
                {{user.username}}님이 접속하셨습니다.
                <a href="{%url 'logout' %}">로그아웃</a>
            {%else%} 
            <a href="{%url 'login'%}">로그인</a>
            {%endif%}
            
            </div>
            <a href=" {%url 'index'%}">
                <h3> PU <br> NB </h3>
           </a>
           <h3 class="menu">MENU</h3>
        </div>
           
        <div class="list-box">
        {% for mymenu in mypub.menulist_set.all %}
        <a href="{% url 'beer' mymenu.id %}">
            <div class="menu_list">
                {% for mybeer in mypub.menudetail_set.all %}
                <img class="image" src="{{mybeer.beerimage.url}}">
                {% endfor %}
                <p>{{mymenu.body}}</p>
            </div>
        </a>
        {% endfor %}
        </div>
        <div class = "comment">
            <hr>
            <form method="post" action="{% url 'create_comment' mypub.id %}">
                {%csrf_token%}
                {%for i in comment_form%}
                        {%if i.label != 'Post' %}
                        댓글: {{i}}
                        {%endif%}
                {%endfor%}
                <input type="hidden" name="post" value={{mypub.id}}>
                <button type="submit">저장</button>
            </form>
            <hr>
            {% for i in mypub.comment_set.all %}
            <p>{{i.author}}: {{i}} <a href="{% url 'delete_comment' i.id mypub.id %}">삭제</a></p>
            <div class = recomment>
            <form method="post" action="{% url 'create_recomment' mypub.id %}">
                {%csrf_token%}
                {%for recom_form in recomment_form%}
                    {%if recom_form.label != 'Comment' %}
                        {%if recom_form.label == '대댓글' %}
                        +대댓글 {{recom_form}}
                        {%endif%}
                    {%endif%}
                {%endfor%}
                <input type="hidden" name="comment" value={{i.id}}>
                <button type="submit">저장</button>
            </form>
            {%for recom in i.recomment_set.all%}
            +{{recom.author}}: {{recom}}
            <a href="{% url 'delete_recomment' recom.id mypub.id %}">삭제</a><br>
            {%endfor%}
            </div>
        <hr>
        {%endfor%}
        </div>
    </div>
</body>
</html>

ohap/info/templates/info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>infopage</title>
</head>
<body>
    {% for i in take_all_Beer %}
    {{i.pubname}}<br>
    {{i.beername}}<br>
    <img src="{{i.beerimage.url}}" width="100px" height="100px"><br>
    {{i.taste}}<br>
    {{i.price}}<br>
    {{i.alcohol}}<br>
    <div>
        <form method="POST" action="{url 'like' %}">
            {% csrf_token %}
            {{like_form}}
        <input type="submit" value="좋아요">
    </form>
    </div>
    {{i.information}}<br>
    {% endfor %}


</body>
</html>